### ISSUE TITLE
Live test status while running test file

### ISSUE THREAD

**Issue by julianYaman** [pierreroth64/jest-spec-reporter#11]
Hello,

is it possible to show the status of a completed test while the whole test file is still running (similar to what `mocha` does)?
Maybe I miss setting any configuration options.

Regards,
Julian Yaman

**Comment by pierreroth64** [comment]
It is the default behavior... would you please provide a repo as an example? Thanks.

**Comment by julianYaman** [comment]
Sadly, I cannot since my current project is closed source. At the end, my goal is to get a similar output, like you can see here: https://github.com/facebook/jest/issues/6616#issuecomment-669817915.

The command I'm currently using for executing the test is `jest --runInBand --verbose``.
And this is my current config:

```js
module.exports = {
    roots: ['./spec'],
    preset: 'ts-jest',
    reporters: [
      "jest-spec-reporter",
      [ "jest-junit", { suiteName: "D365 UI Tests", outputDirectory: "reports", outputName: `junit_${new Date().toISOString().replace(/:/g, "")}.xml` } ]
    ],
    testRegex: '(/__tests__/.*|(\\.|/)(test|spec))\\.tsx?$',
    moduleFileExtensions: ['ts', 'tsx', 'js', 'jsx', 'json', 'node'],
    transformIgnorePatterns: ['<rootDir>/node_modules/'],
    testTimeout: 120000, 
}
```

**Comment by pierreroth64** [comment]
The `--runInBand` option [serializes execution](https://jestjs.io/docs/cli#--runinband). You should try to remove it

**Comment by julianYaman** [comment]
This didn't work for me, already tried it. Should I still use `--verbose`?

**Comment by pierreroth64** [comment]
`verbose` option has nothing to do with serialization of tests. Please create an empty repository reproducing the unexpected behavior.

**Comment by julianYaman** [comment]
Hi, sorry for the late response. Did some research and found out that this might have something to do with me using asynchronous tests (using playwright for Browser UI tests). Using synchronous test resulted into showing the status again.

Unfortunately, I'm now at a new issue that the asynchronous test will not be counted by Jest and will only be shown after the full test suite has ended. But I guess this does not have anything to do with this package.

One of many Jest issues which confirmed my "theory" was this one https://github.com/facebook/jest/issues/10839. Since I need the output for my DevOps pipeline to show the current progress, I already think about switch to `mocha`.

**Comment by julianYaman** [comment]
Since I'm now using `mocha` for the tests, I will close this issue. I hope this is ok for you.
Thanks for your time and help 👍
