### ISSUE TITLE
console.log inside tests/sources not printed

### ISSUE THREAD

**Issue by IgnusG** [pierreroth64/jest-spec-reporter#3]
This makes it difficult to debug tests. Is there any way to include it?

jest-progress-bar-reporter has the same problem.

**Comment by pierreroth64** [comment]
This is not a reporter issue. You should set `verbose: true` in your `jest.config.js`, such as:

```javascript
module.exports = {
  verbose: true,
  testPathIgnorePatterns: ['/node_modules/'],
  reporters: ['jest-spec-reporter']
};
```
